---
variables:
  GO111MODULE: "on"

stages:
  - test

run-tests:
  stage: test
  image: "golang:1.11.1"
  cache:
    paths:
      - "/go/pkg"
  script:
    - "mkdir -p /go/src/gitlab.com/zerok/go-gedcom5"
    - "cp -R * /go/src/gitlab.com/zerok/go-gedcom5/"
    - "cd /go/src/gitlab.com/zerok/go-gedcom5 && go mod download && go test -v -cover ./..."
