---
variables:
  GO111MODULE: "on"

stages:
  - test

run-tests:
  stage: test
  image: "golang:1.11.1"
  cache:
    paths:
      - "_mods"
  script:
    - "mkdir -p /go/src/gitlab.com/zerok/go-gedcom5"
    - "mkdir -p /go/src/gitlab.com/zerok/go-gedcom5/_mods"
    - "mkdir -p /go/pkg/mod"
    - "cp -R * /go/src/gitlab.com/zerok/go-gedcom5/"
    - "cd /go/src/gitlab.com/zerok/go-gedcom5 && cp -R _mods/* /go/pkg/mod/ && go mod download && go test -v -cover ./... && cp -R /go/pkg/mod/* _mods/"
