name: "Test"

on:
  push:
    branches:
      - main

  pull_request: {}

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Set up Go"
        uses: actions/setup-go@v4

      - name: "Run tests"
        run: |
          go test ./... -v 
